[versions]
agp = "9.2.1"
dexkit = "2.2.0"
libxposed-api = "101.0.1"
libxposed-service = "101.0.0"

[libraries]
dexkit = { group = "org.luckypray", name = "dexkit", version.ref = "dexkit" }
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposed-api" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "libxposed-service" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }